name: Nightly Vulnerability Scan

on:
  schedule:
    - cron: '0 23 * * 1-5'
jobs:
  vulnerability_scan:
    name: Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Scan source for Vulnerabilities (govulncheck)
        env:
          GOTOOLCHAIN: local
        run: go -C tools tool govulncheck -C .. ./...
